port: 8081

mongo:
  uri: "mongodb://localhost:27017"
  name: "extensiondb"
  user_collection: "users"
  local_master_key: "rIkvosH58fbF5XdNct9lT8l4hk89MCZj1Lo1scTHHXoCm05YNs2Lu4bpkwlDD/8rLN70VfaVhD4BYtMjK+l+CK8BL8gIa8MEJud0GmkgnTj3p/e/wnJgaK/bqAJAejyh"